phraseapp:
  project_id: 9bc24e0343bd5fb2a850255289cf9265
  file_format: json
  push:
    sources:
    - file: ./public/locales/en.json
      params:
        file_format: json
  pull:
    targets:
    - file: ./public/locales/%{name}.json
      params:
        file_format: json
